//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\realm.DESKTOP-DQ0IJ8Q\Documents\GitHub\instrumentacion\20190528\nuestroduino.py
///  Source class: nuestroIno
///  Generation timestamp: 2019-05-28T19:20:09.337186
///  Class code hash: 8772586d05ab6f0f6d3c4d62f2453d258ff96180
///
/////////////////////////////////////////////////////////////



#include "inodriver_user.h"

void user_setup() {
}

void user_loop() {
}
// COMMAND: LIGHT, FEAT: light
int get_LIGHT() {
  return 0;
};

int set_LIGHT(int value) {
  return 0;
};


