//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; C:\Users\realm.DESKTOP-DQ0IJ8Q\Documents\GitHub\instrumentacion\20190528\nuestroduino.py
///  Source class: nuestroIno
///  Generation timestamp: 2019-05-28T19:20:09.319187
///  Class code hash: 8772586d05ab6f0f6d3c4d62f2453d258ff96180
///
/////////////////////////////////////////////////////////////


#include "inodriver_bridge.h"

SerialCommand sCmd;

void ok() {
  Serial.println("OK");
}

void error(const char* msg) {
  Serial.print("ERROR: ");
  Serial.println(msg);
}

void error_i(int errno) {
  Serial.print("ERROR: ");
  Serial.println(errno);
}

void bridge_loop() {
  while (Serial.available() > 0) {
    sCmd.readSerial();
  }
}

void bridge_setup() {
  //// Setup callbacks for SerialCommand commands

  // All commands might return
  //    ERROR: <error message>

  // All set commands return 
  //    OK 
  // if the operation is successfull

  // All parameters are ascii encoded strings
  sCmd.addCommand("INFO?", getInfo); 

  sCmd.setDefaultHandler(unrecognized); 


  // light
  // <B> bool as string: True as "1", False as "0" 

  // Getter:
  //   LIGHT? 
  // Returns: <B> 
  sCmd.addCommand("LIGHT?", wrapperGet_LIGHT); 

  // Setter:
  //   LIGHT <B> 
  // Returns: OK or ERROR    
  sCmd.addCommand("LIGHT", wrapperSet_LIGHT); 
}

//// Code 

void getInfo() {
  Serial.print("nuestroIno,");
  Serial.println(COMPILE_DATE_TIME);
}

void unrecognized(const char *command) {
  error("Unknown command");
}
//// Auto generated Feat and DictFeat Code
// COMMAND: LIGHT, FEAT: light

void wrapperGet_LIGHT() { 
  Serial.println(get_LIGHT()); 
}; 


void wrapperSet_LIGHT() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int value = atoi(arg);

  int err = set_LIGHT(value);
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};



